# SwiftLint Configuration for iOS Development

# Disabled rules (rules that are turned off)
disabled_rules:
  - trailing_whitespace
  - todo
  - identifier_name

# Enabled rules (explicitly enable important rules)
opt_in_rules:
  # Code style and formatting
  - array_init
  - attributes
  - closure_body_length
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - contains_over_first_not_nil
  - contains_over_range_nil_comparison
  - discouraged_object_literal
  - empty_collection_literal
  - empty_count
  - empty_string
  - enum_case_associated_values_count
  - explicit_init
  - extension_access_modifier
  - fallthrough
  - fatal_error_message
  - file_header
  - file_name
  - first_where
  - force_unwrapping
  - function_default_parameter_at_end
  - identical_operands
  - implicit_return
  - joined_default_parameter
  - last_where
  - legacy_random
  - literal_expression_end_indentation
  - lower_acl_than_parent
  - modifier_order
  - nimble_operator
  - nslocalizedstring_key
  - number_separator
  - object_literal
  - operator_usage_whitespace
  - overridden_super_call
  - override_in_extension
  - pattern_matching_keywords
  - prefer_self_type_over_type_of_self
  - prefer_zero_over_explicit_init
  - prefixed_toplevel_constant
  - prohibited_interface_builder
  - prohibited_super_call
  - quick_discouraged_call
  - quick_discouraged_focused_test
  - quick_discouraged_pending_test
  - reduce_into
  - redundant_nil_coalescing
  - redundant_type_annotation
  - required_enum_case
  - single_test_class
  - sorted_first_last
  - sorted_imports
  - static_operator
  - strong_iboutlet
  - switch_case_on_newline
  - toggle_bool
  - unavailable_function
  - unneeded_parentheses_in_closure_argument
  - untyped_error_in_catch
  - vertical_parameter_alignment_on_call
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces
  - xct_specific_matcher
  - yoda_condition

# Rule configurations
line_length:
  warning: 200
  error: 250
  ignores_urls: true
  ignores_function_declarations: true
  ignores_comments: true

type_body_length:
  warning: 300
  error: 400

function_body_length:
  warning: 50
  error: 100

function_parameter_count:
  warning: 5
  error: 8

cyclomatic_complexity:
  warning: 10
  error: 20

nesting:
  type_level:
    warning: 3
    error: 6
  statement_level:
    warning: 5
    error: 10

identifier_name:
  min_length:
    warning: 2
    error: 1
  max_length:
    warning: 40
    error: 60
  excluded:
    - id
    - URL
    - GlobalAPIKey

type_name:
  min_length:
    warning: 3
    error: 1
  max_length:
    warning: 40
    error: 60

file_header:
  required_pattern: |
                    \/\/
                    \/\/  .*\.swift
                    \/\/  Viaplay
                    \/\/
                    \/\/  Created by .* on \d{1,2}\/\d{1,2}\/\d{4}\.
                    \/\/  Copyright © \d{4} Viaplay\. All rights reserved\.
                    \/\/

file_name:
  excluded:
    - "*.generated.swift"
    - "*.pb.swift"

# Paths to include/exclude
included:
  - Viaplay

excluded:
  - Carthage
  - Pods
  - DerivedData
  - ViaplayTests
  - "*.generated.swift"
  - "*.pb.swift"

# Reporter type (xcode, json, csv, checkstyle, junit, html, emoji, sonarqube, markdown)
reporter: "xcode"
