coverage:
  status:
    project:
      default:
        target: 80%
        threshold: 5%
    patch:
      default:
        target: 80%
        threshold: 5%

comment:
  layout: "header,diff,files,footer"
  behavior: default
  require_changes: false

github_checks:
  annotations: true

ignore:
  - "Viaplay/ViaplayTests/**"
  - "**/Tests/**"
  - "**/*Tests.swift"
  - "**/*Test.swift"
  - "**/Mocks.swift"
  - "**/Stubs.swift"
  - "**/Preview Content/**"
  - "**/Assets.xcassets/**"
  - "**/*.entitlements"
  - "**/App/**"

codecov:
  require_ci_to_pass: yes

